server:
  port: 8080
  #context-path: /

spring:
  application:
    name: demo-tkmybatis
  profiles.active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MySQL
  #mappers: cn.sisyphe.demo.core.mapper.BaseMapper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true

---
spring:
  profiles: prod
  datasource:
    initialize: false

---
spring:
  profiles: dev
  datasource:
    initialize: false
    url: 'jdbc:mysql://localhost:3306/bim?useUnicode=true&characterEncoding=utf-8&useSSL=false'
    username: 'root'
    password:
    dbcp2:
      min-idle: 5
      max-idle: 10
      initial-size: 10
      max-total: 20
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
#    username: test
#    password: 123456

---
spring:
  profiles: test
  datasource:
    initialize: true
    url: 'jdbc:mysql://192.168.21.141:3306/demo_ly?useUnicode=true&characterEncoding=utf-8&useSSL=false'
    username: root
    password: 123456
